### ISSUE TITLE
Fontconfig: python error?

### ISSUE THREAD

**Issue by 1480c1** [jb-alvarado/media-autobuild_suite#1107]
Probably something upstream somewhere. Creating in case someone else sees this error.
```
  GEN      fcblanks.h
  GEN      ../../fc-blanks/.gitignore
Traceback (most recent call last):
  File "../../fc-blanks/fc-blanks.py", line 23, in <module>
    dom = html.fromstring(data)
  File "C:/Users/travis/build/1480c1/media-autobuild_suite/msys64/mingw64/lib/python2.7/site-packages/lxml/html/__init__.py", line 875, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "C:/Users/travis/build/1480c1/media-autobuild_suite/msys64/mingw64/lib/python2.7/site-packages/lxml/html/__init__.py", line 764, in document_fromstring
```
from <https://travis-ci.com/1480c1/media-autobuild_suite/jobs/180099767> (I may need to look at the logging system for noMintty again.)
[logs.zip](https://0x0.st/z-qO.zip)

**Comment by 1480c1** [comment]
```
18:04:04   Running git clone for fontconfig...
18:04:12 ┌ fontconfig git ........................... [Recently updated]
18:04:13 Installing python2-lxml... done
18:05:08 Installing python2-six... done
18:05:11 ├ Running autogen...
18:05:43 ├ Running configure...
18:07:08 ├ Running make...
18:09:24 ├ Running install...
18:09:34 ├ Stripping...
18:09:34 └ fontconfig-git .................................... [Updated]
```
seems like it disappeared. Reseting, right now.

**Comment by wiiaboo** [comment]
It's a constant issue because they download stuff during compilation and parse it with python. Sometimes it's 404 and it breaks compilation because their code can't handle that.

**Comment by 1480c1** [comment]
I see. At first I thought something was wrong with my computer, but guess it was just their issue.
