### ISSUE TITLE
FAILED: vk_enum_string_helper.h 

### ISSUE THREAD

**Issue by weezzelboy** [jb-alvarado/media-autobuild_suite#1152]
cmd.exe /C "cd /D C:\MABS\build\vulkan-loader-git\build-64bit && C:\MABS\msys64\mingw64\bin\python3.exe C:/MABS/build/vulkan-loader-git/scripts/loader_genvk.py -registry C:/MABS/local64/share/vulkan/registry/vk.xml -scripts C:/MABS/local64/share/vulkan/registry vk_enum_string_helper.h"
Traceback (most recent call last):
  File "C:/MABS/build/vulkan-loader-git/scripts/loader_genvk.py", line 500, in <module>
    genTarget(args)
  File "C:/MABS/build/vulkan-loader-git/scripts/loader_genvk.py", line 375, in genTarget
    reg.apiGen(options)
  File "C:/MABS/local64/share/vulkan/registry\reg.py", line 943, in apiGen
    regEmitExtensions = re.compile(self.genOpts.emitExtensions)
  File "C:/MABS/msys64/mingw64/lib/python3.7\re.py", line 234, in compile
    return _compile(pattern, flags)
  File "C:/MABS/msys64/mingw64/lib/python3.7\re.py", line 285, in _compile
    raise TypeError("first argument must be string or compiled pattern")
TypeError: first argument must be string or compiled pattern
ninja: build stopped: subcommand failed.

[logs.zip](https://0x0.st/zKF-.zip)

**Comment by 1480c1** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/issues/1147
